<a href="https://colab.research.google.com/github/MdSufiyan005/DeepLearning-Tensorflow/blob/main/Tensorflow_Deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Tensors are data structures used in machine learning to represent input data and output data in Machine Learning models. They are buckets of numbers of a specific shape and a certain rank (dimensionality). Tensors are used by neural networks as components to describe and calculate phenomena. In machine learning, tensors are used to represent data with different dimensions, such as pixels in a photo. Tensors are represented as lists or arrays of arrays.

In [ ]:
scalar = tf.constant(7) ## Creating scalar
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
Matrices = tf.constant([[10,7],[7,10]]) ## Creating Matrices
Matrices

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
Matrices.ndim

2

In [ ]:
Tensors = tf.constant([[[1,2,3],[5,6,4]],  ## Creating Tensor

                        [[6,5,4],[4,5,9]],

                       [[6,8,9],[4,2,8]]])
Tensors

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [5, 6, 4]],

       [[6, 5, 4],
        [4, 5, 9]],

       [[6, 8, 9],
        [4, 2, 8]]], dtype=int32)>

In [ ]:
Tensors.ndim ## ndim for knowing its dimension

3

In [ ]:
# Creating Tensors Using tf.Variables
changable_tensor = tf.Variable([10,7])
nonchangable_tensor = tf.constant([10,7])

changable_tensor[0].assign(5) ## We can change the values of tensors by using tf.Variables and using .assign



<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [ ]:
nonchangable_tensor[0].assign(1)  ## while using tf.constant we cannot change the values of the tensors

In [ ]:
## Creating  Random Tensors
## Random tensors are tensors of some arbitrary size that contain a random number

## create two random tensors

random1 = tf.random.Generator.from_seed(42)
random1 =random1.normal(shape=(3,2))

random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3,2))

random1,random2, random1 == random2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [23]:
### shuffle the orders of elements in a tensor

not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [27]:
tf.random.shuffle(not_shuffled,seed =40)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>